//! Family-standard adoption metadata verification.
//!
//! The repository declares its adoption of the Agent MCP family standard in
//! two places: the product-owned `family.toml` profile declaration and the
//! `.family/manifest.json` record of the explicitly managed adoption files.
//! The manifest pins the SHA-256 of every managed file so a future template
//! update can run an honest three-way review (adopted baseline bytes, current
//! repository bytes, next template bytes) without claiming the repository was
//! generated by any initializer.

use crate::release::digest;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// The only manifest schema this verifier understands.
const MANIFEST_SCHEMA_VERSION: u64 = 1;

/// The only adoption mode this verifier accepts: a manual, reviewable
/// alignment against a pinned template revision.
const ADOPTION_MODE: &str = "manual";

/// Path of the adoption manifest relative to the repository root.
const MANIFEST_PATH: &str = ".family/manifest.json";

/// Path of the family declaration relative to the repository root.
const FAMILY_PATH: &str = "family.toml";

/// One explicitly managed adoption file with its pinned digest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManagedFile {
    /// Repository-relative path of the managed file.
    pub path: String,
    /// Why the adoption manages this file (for example `declaration`).
    pub role: String,
    /// Whether the bytes originated from the template or the product.
    pub origin: String,
    /// Lowercase SHA-256 of the current managed bytes.
    pub sha256: String,
}

/// The parsed `.family/manifest.json` adoption record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    /// Manifest format version; only `1` is understood.
    pub schema_version: u64,
    /// How the adoption happened; only `manual` is accepted.
    pub adoption: String,
    /// Family standard revision the repository aligns with.
    pub standard_version: String,
    /// Full commit SHA of the private template revision reviewed for adoption.
    pub template_revision: String,
    /// Managed adoption files with pinned digests.
    pub managed: Vec<ManagedFile>,
}

impl Manifest {
    /// Loads and validates the manifest stored under `root`.
    ///
    /// Fails with one actionable message when the file is missing, malformed,
    /// uses an unknown schema or mode, has a malformed pinned revision or digest,
    /// lists itself, repeats a path, or names an empty/non-relative path.
    pub fn load(root: &Path) -> Result<Self, String> {
        let path = root.join(MANIFEST_PATH);
        let bytes = std::fs::read(&path)
            .map_err(|error| format!("{} must be readable: {error}", path.display()))?;
        let manifest: Manifest = serde_json::from_slice(&bytes).map_err(|error| {
            format!("{} must be valid adoption metadata: {error}", MANIFEST_PATH)
        })?;
        if manifest.schema_version != MANIFEST_SCHEMA_VERSION {
            return Err(format!(
                "{MANIFEST_PATH} schema_version must be {MANIFEST_SCHEMA_VERSION}"
            ));
        }
        if manifest.adoption != ADOPTION_MODE {
            return Err(format!(
                "{MANIFEST_PATH} adoption must be \"{ADOPTION_MODE}\"; this repository was aligned by review, not generated"
            ));
        }
        if manifest.template_revision.len() != 40
            || !manifest
                .template_revision
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return Err(format!(
                "{MANIFEST_PATH} template_revision must pin a full lowercase commit SHA"
            ));
        }
        if manifest.managed.is_empty() {
            return Err(format!("{MANIFEST_PATH} must manage at least one file"));
        }
        let mut seen = std::collections::BTreeSet::new();
        for file in &manifest.managed {
            if file.path.is_empty()
                || !Path::new(&file.path)
                    .components()
                    .all(|part| matches!(part, std::path::Component::Normal(_)))
            {
                return Err(format!(
                    "managed file {} must be a nonempty repository-relative path without traversal",
                    file.path
                ));
            }
            if file.path == MANIFEST_PATH {
                return Err(format!(
                    "{MANIFEST_PATH} must not hash itself; pin only the managed files"
                ));
            }
            if file.sha256.len() != 64
                || !file
                    .sha256
                    .bytes()
                    .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
            {
                return Err(format!(
                    "managed file {} must pin a 64-character lowercase SHA-256",
                    file.path
                ));
            }
            if !seen.insert(file.path.as_str()) {
                return Err(format!("managed file {} is listed twice", file.path));
            }
        }
        Ok(manifest)
    }
}

/// Verifies every managed adoption file against its pinned digest and the
/// family declaration against the manifest.
///
/// Read-only: nothing in the repository is modified. The error message names
/// the first broken invariant so a failed gate is immediately actionable.
pub fn verify(root: &Path) -> Result<(), String> {
    let manifest = Manifest::load(root)?;
    for file in &manifest.managed {
        let path = root.join(&file.path);
        let actual =
            digest(&path).map_err(|error| format!("managed file {}: {error}", file.path))?;
        if actual != file.sha256 {
            return Err(format!(
                "managed file {} changed (manifest {}, file {}); rerun `cargo xtask family update` after review",
                file.path, file.sha256, actual
            ));
        }
    }
    let declaration = std::fs::read_to_string(root.join(FAMILY_PATH))
        .map_err(|error| format!("{FAMILY_PATH} must be readable: {error}"))?;
    let declaration: toml::Value = toml::from_str(&declaration)
        .map_err(|error| format!("{FAMILY_PATH} must be valid TOML: {error}"))?;
    let declared_standard = declaration
        .get("standard_version")
        .and_then(toml::Value::as_str)
        .unwrap_or_default();
    if declared_standard != manifest.standard_version {
        return Err(format!(
            "{FAMILY_PATH} standard_version \"{declared_standard}\" must match {MANIFEST_PATH} \"{}\"",
            manifest.standard_version
        ));
    }
    Ok(())
}

/// Rewrites the pinned digests of the currently managed files.
///
/// The path list itself is deliberately not touched: adding or removing a
/// managed file is a reviewed manifest edit, while `update` only records the
/// new bytes of files already adopted. The manifest is rewritten only when a
/// digest actually changed.
pub fn update(root: &Path) -> Result<(), String> {
    let mut manifest = Manifest::load(root)?;
    let mut changed = false;
    for file in &mut manifest.managed {
        let path: PathBuf = root.join(&file.path);
        let actual =
            digest(&path).map_err(|error| format!("managed file {}: {error}", file.path))?;
        if actual != file.sha256 {
            file.sha256 = actual;
            changed = true;
        }
    }
    if changed {
        let bytes = serde_json::to_vec_pretty(&manifest)
            .map_err(|error| format!("adoption manifest must serialize: {error}"))?;
        std::fs::write(root.join(MANIFEST_PATH), bytes)
            .map_err(|error| format!("{MANIFEST_PATH} must be writable: {error}"))?;
    }
    Ok(())
}

/// Exports or verifies current discovery snapshots from the same domain registries
/// used by live MCP. `export` only writes these three generated files; `check`
/// compares complete JSON including descriptions, schemas and typed annotations.
/// The descriptor contains names, never environment values or capability secrets.
pub fn contract(root: &Path, export: bool) -> Result<(), String> {
    let descriptor = serde_json::json!({
        "schema_version": 1,
        "product_version": env!("CARGO_PKG_VERSION"),
        "sdk": {"name": "rmcp", "version": "3.4.0"},
        "protocol_versions": ["2024-11-05", "2025-03-26", "2025-06-18", "2025-11-25"],
        "operator": {
            "server_name": "agent-run", "registration_name": "agent-run",
            "transport": "stdio", "command": "agent-run", "args": ["mcp"],
            "optional_environment_names": ["AGENT_RUN_HOME"],
            "startup_timeout_seconds": null, "tool_timeout_seconds": null,
            "timeout_policy": "Host chooses startup/call deadlines; cancellation abandons the wait, not admitted work."
        },
        "worker": {
            "server_name": "agent-run-worker",
            "registration_name": agent_run_domain::worker::SERVER_NAME,
            "transport": "stdio", "command": "agent-run", "args": ["_worker-mcp"],
            "required_environment_names": agent_run_domain::worker::ENV_NAMES,
            "startup_timeout_seconds": null, "tool_timeout_seconds": null,
            "supervisor_only": true,
            "timeout_policy": "Supervisor supplies attempt capability; cancelled waits do not undo durable enqueue."
        }
    });
    for (path, value) in [
        (
            "schemas/tools.json",
            serde_json::json!(agent_run_domain::tools::tools_json()),
        ),
        (
            "schemas/worker-tools.json",
            serde_json::json!(agent_run_domain::tools::worker_tools_json()),
        ),
        ("schemas/mcp-registration.json", descriptor),
    ] {
        let mut bytes =
            serde_json::to_vec_pretty(&value).map_err(|_| "contract serialization failed")?;
        bytes.push(b'\n');
        if export {
            std::fs::create_dir_all(root.join("schemas"))
                .map_err(|_| "schema directory unavailable")?;
            std::fs::write(root.join(path), bytes)
                .map_err(|_| format!("{path} must be writable"))?;
        } else if std::fs::read(root.join(path))
            .map_err(|_| format!("{path} missing; run cargo xtask contract export"))?
            != bytes
        {
            return Err(format!(
                "{path} drifted; review cargo xtask contract export"
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{MANIFEST_PATH, Manifest, verify};
    use serde_json::json;
    use std::fs;
    use tempfile::tempdir;

    /// Writes one valid adoption manifest over the given managed files.
    fn manifest_for(root: &std::path::Path, files: &[(&str, &str)]) {
        let managed: Vec<_> = files
            .iter()
            .map(|(path, bytes)| {
                json!({
                    "path": path,
                    "role": "declaration",
                    "origin": "product",
                    "sha256": sha256_of(bytes),
                })
            })
            .collect();
        let document = json!({
            "schema_version": 1,
            "adoption": "manual",
            "standard_version": "1.0.0-rc.2",
            "template_revision": "7f094e0463c0a6d5cf52d68d91ca32f6bc0f465f",
            "managed": managed,
        });
        fs::create_dir_all(root.join(".family")).unwrap();
        fs::write(
            root.join(MANIFEST_PATH),
            serde_json::to_vec_pretty(&document).unwrap(),
        )
        .unwrap();
        fs::write(
            root.join("family.toml"),
            "standard_version = \"1.0.0-rc.2\"\n",
        )
        .unwrap();
    }

    /// Lowercase SHA-256 hex digest of `bytes`, matching the release digest.
    fn sha256_of(bytes: &str) -> String {
        crate::release::digest_bytes(bytes.as_bytes())
    }

    /// Writes one managed fixture file, creating its parent directory.
    fn adopted(root: &std::path::Path, path: &str, bytes: &str) {
        let target = root.join(path);
        fs::create_dir_all(target.parent().unwrap()).unwrap();
        fs::write(target, bytes).unwrap();
    }

    /// A manifest whose files still match verifies without changing anything.
    #[test]
    fn matching_manifest_verifies() {
        let root = tempdir().unwrap();
        adopted(
            root.path(),
            "family.toml",
            "standard_version = \"1.0.0-rc.2\"\n",
        );
        adopted(root.path(), "docs/family-standard.md", "summary\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        verify(root.path()).expect("matching adoption metadata verifies");
    }

    /// A changed managed file fails verification and names the file.
    #[test]
    fn changed_managed_file_fails_with_its_path() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "edited\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let error = verify(root.path()).expect_err("drifted digest must fail");
        assert!(error.contains("docs/family-standard.md"), "{error}");
        assert!(error.contains("family update"), "{error}");
    }

    /// A missing managed file is a verification failure, not a silent skip.
    #[test]
    fn missing_managed_file_fails() {
        let root = tempdir().unwrap();
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let error = verify(root.path()).expect_err("missing managed file must fail");
        assert!(error.contains("docs/family-standard.md"), "{error}");
    }

    /// The manifest may not pin itself, mirroring the release checksum rule.
    #[test]
    fn manifest_rejects_hashing_itself() {
        let root = tempdir().unwrap();
        manifest_for(root.path(), &[(MANIFEST_PATH, "{}\n")]);
        let error = Manifest::load(root.path()).expect_err("self-hash must be rejected");
        assert!(error.contains("must not hash itself"), "{error}");
    }

    /// Drift between the declaration and the manifest standard version fails.
    #[test]
    fn declaration_must_match_manifest_standard_version() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "summary\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        adopted(
            root.path(),
            "family.toml",
            "standard_version = \"1.0.0-rc.3\"\n",
        );
        let error = verify(root.path()).expect_err("version drift must fail");
        assert!(error.contains("1.0.0-rc.3"), "{error}");
        assert!(error.contains("1.0.0-rc.2"), "{error}");
    }

    /// An initializer-style provenance claim is refused outright.
    #[test]
    fn generated_provenance_is_refused() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "summary\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let raw = fs::read_to_string(root.path().join(MANIFEST_PATH)).unwrap();
        fs::write(
            root.path().join(MANIFEST_PATH),
            raw.replace("\"manual\"", "\"init.sh\""),
        )
        .unwrap();
        let error = Manifest::load(root.path()).expect_err("non-manual adoption must fail");
        assert!(error.contains("manual"), "{error}");
    }

    /// Malformed pins and paths fail before any managed file is read or updated.
    #[test]
    fn malformed_manifest_pins_and_paths_are_refused() {
        let root = tempdir().unwrap();
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let raw = fs::read_to_string(root.path().join(MANIFEST_PATH)).unwrap();
        let valid: serde_json::Value = serde_json::from_str(&raw).unwrap();
        for field in ["template_revision", "sha256", "path"] {
            let invalid = match field {
                "template_revision" => {
                    vec!["short", "ABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFAB"]
                }
                "sha256" => vec![
                    "short",
                    "ABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFAB",
                ],
                _ => vec!["", "/outside", "../outside", "docs/../outside"],
            };
            for value in invalid {
                let mut document = valid.clone();
                if field == "template_revision" {
                    document[field] = json!(value);
                } else {
                    document["managed"][0][field] = json!(value);
                }
                fs::write(root.path().join(MANIFEST_PATH), document.to_string()).unwrap();
                Manifest::load(root.path()).expect_err("malformed manifest must fail");
                super::update(root.path()).expect_err("update must reject malformed manifest");
                assert_eq!(
                    fs::read_to_string(root.path().join(MANIFEST_PATH)).unwrap(),
                    document.to_string(),
                    "rejected update must not rewrite metadata"
                );
            }
        }
    }

    /// `update` records new bytes only for already-managed paths.
    #[test]
    fn update_rewrites_only_pinned_digests() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "edited\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        super::update(root.path()).expect("update refreshes digests");
        verify(root.path()).expect("refreshed manifest verifies");
    }

    /// Exported schemas and registration are deterministic; description,
    /// annotation and input drift each fail the read-only contract gate.
    #[test]
    fn contract_export_detects_all_discovery_drift() {
        let root = tempdir().unwrap();
        super::contract(root.path(), true).unwrap();
        super::contract(root.path(), false).unwrap();
        let path = root.path().join("schemas/tools.json");
        let original = fs::read(&path).unwrap();
        for field in ["description", "annotations", "inputSchema"] {
            let mut tools: serde_json::Value = serde_json::from_slice(&original).unwrap();
            tools[0][field] = json!("drift");
            fs::write(&path, tools.to_string()).unwrap();
            assert!(
                super::contract(root.path(), false)
                    .unwrap_err()
                    .contains("drifted")
            );
            assert_eq!(fs::read_to_string(&path).unwrap(), tools.to_string());
        }
        super::contract(root.path(), true).unwrap();
        assert_eq!(fs::read(&path).unwrap(), original);
        super::contract(root.path(), false).unwrap();
    }
}
