//! Family-standard adoption metadata verification.
//!
//! The repository declares its adoption of the Agent MCP family standard in
//! two places: the product-owned `family.toml` profile declaration and the
//! `.family/manifest.json` record of the explicitly managed adoption files.
//! The manifest pins the SHA-256 of every managed file so a future template
//! update can run an honest three-way review (adopted baseline bytes, current
//! repository bytes, next template bytes) without claiming the repository was
//! generated by any initializer.

use crate::release::digest;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// The only manifest schema this verifier understands.
const MANIFEST_SCHEMA_VERSION: u64 = 1;

/// The only adoption mode this verifier accepts: a manual, reviewable
/// alignment against a pinned template revision.
const ADOPTION_MODE: &str = "manual";

/// Path of the adoption manifest relative to the repository root.
const MANIFEST_PATH: &str = ".family/manifest.json";

/// Path of the family declaration relative to the repository root.
const FAMILY_PATH: &str = "family.toml";

/// One explicitly managed adoption file with its pinned digest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManagedFile {
    /// Repository-relative path of the managed file.
    pub path: String,
    /// Why the adoption manages this file (for example `declaration`).
    pub role: String,
    /// Whether the bytes originated from the template or the product.
    pub origin: String,
    /// Lowercase SHA-256 of the current managed bytes.
    pub sha256: String,
}

/// The parsed `.family/manifest.json` adoption record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    /// Manifest format version; only `1` is understood.
    pub schema_version: u64,
    /// How the adoption happened; only `manual` is accepted.
    pub adoption: String,
    /// Family standard revision the repository aligns with.
    pub standard_version: String,
    /// Full commit SHA of the private template revision reviewed for adoption.
    pub template_revision: String,
    /// Managed adoption files with pinned digests.
    pub managed: Vec<ManagedFile>,
}

impl Manifest {
    /// Loads and validates the manifest stored under `root`.
    ///
    /// Fails with one actionable message when the file is missing, malformed,
    /// uses an unknown schema or mode, has a malformed pinned revision or digest,
    /// lists itself, repeats a path, or names an empty/non-relative path.
    pub fn load(root: &Path) -> Result<Self, String> {
        let path = root.join(MANIFEST_PATH);
        let bytes = std::fs::read(&path)
            .map_err(|error| format!("{} must be readable: {error}", path.display()))?;
        let manifest: Manifest = serde_json::from_slice(&bytes).map_err(|error| {
            format!("{} must be valid adoption metadata: {error}", MANIFEST_PATH)
        })?;
        if manifest.schema_version != MANIFEST_SCHEMA_VERSION {
            return Err(format!(
                "{MANIFEST_PATH} schema_version must be {MANIFEST_SCHEMA_VERSION}"
            ));
        }
        if manifest.adoption != ADOPTION_MODE {
            return Err(format!(
                "{MANIFEST_PATH} adoption must be \"{ADOPTION_MODE}\"; this repository was aligned by review, not generated"
            ));
        }
        if manifest.template_revision.len() != 40
            || !manifest
                .template_revision
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return Err(format!(
                "{MANIFEST_PATH} template_revision must pin a full lowercase commit SHA"
            ));
        }
        if manifest.managed.is_empty() {
            return Err(format!("{MANIFEST_PATH} must manage at least one file"));
        }
        let mut seen = std::collections::BTreeSet::new();
        for file in &manifest.managed {
            if file.path.is_empty()
                || !Path::new(&file.path)
                    .components()
                    .all(|part| matches!(part, std::path::Component::Normal(_)))
            {
                return Err(format!(
                    "managed file {} must be a nonempty repository-relative path without traversal",
                    file.path
                ));
            }
            if file.path == MANIFEST_PATH {
                return Err(format!(
                    "{MANIFEST_PATH} must not hash itself; pin only the managed files"
                ));
            }
            if file.sha256.len() != 64
                || !file
                    .sha256
                    .bytes()
                    .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
            {
                return Err(format!(
                    "managed file {} must pin a 64-character lowercase SHA-256",
                    file.path
                ));
            }
            if !seen.insert(file.path.as_str()) {
                return Err(format!("managed file {} is listed twice", file.path));
            }
        }
        Ok(manifest)
    }
}

/// Verifies every managed adoption file against its pinned digest and the
/// family declaration against the manifest.
///
/// Read-only: nothing in the repository is modified. The error message names
/// the first broken invariant so a failed gate is immediately actionable.
pub fn verify(root: &Path) -> Result<(), String> {
    let manifest = Manifest::load(root)?;
    for file in &manifest.managed {
        let path = root.join(&file.path);
        let actual =
            digest(&path).map_err(|error| format!("managed file {}: {error}", file.path))?;
        if actual != file.sha256 {
            return Err(format!(
                "managed file {} changed (manifest {}, file {}); rerun `cargo xtask family update` after review",
                file.path, file.sha256, actual
            ));
        }
    }
    let declaration = std::fs::read_to_string(root.join(FAMILY_PATH))
        .map_err(|error| format!("{FAMILY_PATH} must be readable: {error}"))?;
    let declaration: toml::Value = toml::from_str(&declaration)
        .map_err(|error| format!("{FAMILY_PATH} must be valid TOML: {error}"))?;
    let declared_standard = declaration
        .get("standard_version")
        .and_then(toml::Value::as_str)
        .unwrap_or_default();
    if declared_standard != manifest.standard_version {
        return Err(format!(
            "{FAMILY_PATH} standard_version \"{declared_standard}\" must match {MANIFEST_PATH} \"{}\"",
            manifest.standard_version
        ));
    }
    Ok(())
}

/// Reads one repository TOML document for structural checks without rewriting it.
fn toml_file(root: &Path, path: &str) -> Result<toml::Value, String> {
    let text =
        std::fs::read_to_string(root.join(path)).map_err(|_| format!("{path} is unreadable"))?;
    toml::from_str(&text).map_err(|_| format!("{path} is not valid TOML"))
}

/// Checks only inspectable project structure, in addition to the existing digest
/// and discovery comparisons. Passing proves no business semantics, host readiness
/// or release qualification; all operations are read-only.
pub fn check(root: &Path) -> Result<(), String> {
    verify(root)?;
    contract(root, false)?;
    project_conformance(root)
}

/// Returns one nested TOML value or a fixed empty scalar, so missing malformed
/// declarations produce typed check failures rather than indexing panics.
fn toml_at<'a>(value: &'a toml::Value, keys: &[&str]) -> &'a toml::Value {
    static MISSING: toml::Value = toml::Value::String(String::new());
    keys.iter()
        .try_fold(value, |value, key| value.get(*key))
        .unwrap_or(&MISSING)
}

/// Verifies Cargo inheritance/pins, explicit workflow policy and registry shapes.
/// Separate from verify so minimal adoption fixtures retain their hash-only contract.
fn project_conformance(root: &Path) -> Result<(), String> {
    let cargo = toml_file(root, "Cargo.toml")?;
    let workspace = toml_at(&cargo, &["workspace"]);
    let package = toml_at(workspace, &["package"]);
    if toml_at(workspace, &["resolver"]).as_str() != Some("3")
        || toml_at(package, &["edition"]).as_str() != Some("2024")
        || toml_at(package, &["publish"]).as_bool() != Some(false)
    {
        return Err("Cargo workspace requires resolver 3, edition 2024 and publish=false".into());
    }
    let version = toml_at(package, &["version"])
        .as_str()
        .filter(|v| !v.is_empty())
        .ok_or("workspace package version is missing")?;
    let channel = toml_at(package, &["rust-version"])
        .as_str()
        .ok_or("workspace rust-version is missing")?;
    if channel.split('.').count() != 3
        || channel.split('.').any(|part| part.parse::<u32>().is_err())
    {
        return Err("workspace rust-version must pin a full stable toolchain".into());
    }
    let toolchain = toml_file(root, "rust-toolchain.toml")?;
    if toml_at(&toolchain, &["toolchain", "channel"]).as_str() != Some(channel) {
        return Err("rust-toolchain.toml must match workspace rust-version".into());
    }
    for component in ["rustfmt", "clippy"] {
        if !toml_at(&toolchain, &["toolchain", "components"])
            .as_array()
            .is_some_and(|list| list.iter().any(|value| value.as_str() == Some(component)))
        {
            return Err(format!("pinned toolchain must include {component}"));
        }
    }
    if toml_at(workspace, &["lints", "rust", "unsafe_op_in_unsafe_fn"]).as_str() != Some("deny")
        || toml_at(
            workspace,
            &["lints", "clippy", "undocumented_unsafe_blocks"],
        )
        .as_str()
            != Some("deny")
    {
        return Err("workspace must deny unsafe operations and undocumented unsafe blocks".into());
    }
    let declaration = toml_file(root, FAMILY_PATH)?;
    let product = toml_at(&declaration, &["product"])
        .as_str()
        .ok_or("family product is missing")?;
    let mut product_found = false;
    for member in toml_at(workspace, &["members"])
        .as_array()
        .ok_or("workspace members are missing")?
    {
        let member = member
            .as_str()
            .ok_or("workspace member must be a relative path")?;
        if !Path::new(member)
            .components()
            .all(|part| matches!(part, std::path::Component::Normal(_)))
        {
            return Err("workspace member must stay inside the repository".into());
        }
        let path = format!("{member}/Cargo.toml");
        let manifest = toml_file(root, &path)?;
        if toml_at(&manifest, &["package", "name"]).as_str() == Some(product) {
            product_found = true;
        }
        for field in ["version", "edition", "publish", "license", "rust-version"] {
            if toml_at(&manifest, &["package", field, "workspace"]).as_bool() != Some(true) {
                return Err(format!(
                    "{path} must inherit package.{field} from workspace ({version})"
                ));
            }
        }
        if toml_at(&manifest, &["lints", "workspace"]).as_bool() != Some(true) {
            return Err(format!("{path} must inherit workspace lints"));
        }
    }
    if !product_found {
        return Err("family product must name a workspace package".into());
    }
    let rmcp = toml_at(workspace, &["dependencies", "rmcp", "version"])
        .as_str()
        .and_then(|version| version.strip_prefix('='))
        .ok_or("rmcp must use an exact =version pin")?;
    let lock = toml_file(root, "Cargo.lock")?;
    if !toml_at(&lock, &["package"])
        .as_array()
        .is_some_and(|packages| {
            packages.iter().any(|package| {
                toml_at(package, &["name"]).as_str() == Some("rmcp")
                    && toml_at(package, &["version"]).as_str() == Some(rmcp)
            })
        })
    {
        return Err("Cargo.lock rmcp version must match the exact workspace pin".into());
    }
    let workflows = std::fs::read_dir(root.join(".github/workflows"))
        .map_err(|_| "workflow directory is unreadable")?;
    let mut count = 0;
    for entry in workflows {
        let entry = entry.map_err(|_| "workflow directory entry is unreadable")?;
        let path = entry.path();
        if !matches!(
            path.extension().and_then(|value| value.to_str()),
            Some("yml" | "yaml")
        ) {
            continue;
        }
        count += 1;
        let text = std::fs::read_to_string(&path).map_err(|_| "workflow is unreadable")?;
        workflow_structure(&text).map_err(|error| format!("{}: {error}", path.display()))?;
    }
    if count == 0 {
        return Err("at least one GitHub workflow is required".into());
    }
    for path in ["schemas/tools.json", "schemas/worker-tools.json"] {
        let bytes = std::fs::read(root.join(path)).map_err(|_| format!("{path} is unreadable"))?;
        let registry: serde_json::Value =
            serde_json::from_slice(&bytes).map_err(|_| format!("{path} is invalid JSON"))?;
        registry_structure(&registry).map_err(|error| format!("{path}: {error}"))?;
    }
    Ok(())
}

/// Enforces full SHA pins for remote uses entries and an explicit top-level
/// permissions mapping. This supports the repository's plain YAML keys and
/// does not interpret actions, shell bodies or claim effective runtime authority.
fn workflow_structure(text: &str) -> Result<(), String> {
    if !text
        .lines()
        .any(|line| line == "permissions:" || line.trim_end() == "permissions: {}")
    {
        return Err("workflow must declare top-level permissions explicitly".into());
    }
    let lines: Vec<_> = text.lines().collect();
    for (index, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed.starts_with('#') {
            continue;
        }
        let action = trimmed
            .strip_prefix("- uses:")
            .or_else(|| trimmed.strip_prefix("uses:"));
        if let Some(action) = action {
            let action = action
                .split('#')
                .next()
                .unwrap_or("")
                .trim()
                .trim_matches(['"', '\'']);
            if action.starts_with("./") {
                continue;
            }
            let (_, pin) = action
                .rsplit_once('@')
                .ok_or("remote action must pin a full commit SHA")?;
            if pin.len() != 40 || !pin.bytes().all(|byte| byte.is_ascii_hexdigit()) {
                return Err("remote action must pin a full commit SHA".into());
            }
        }
        if trimmed == "permissions:" {
            let indent = line.len() - line.trim_start().len();
            let mut entries = 0;
            for permission in &lines[index + 1..] {
                let value = permission.trim();
                if value.is_empty() || value.starts_with('#') {
                    continue;
                }
                if permission.len() - permission.trim_start().len() <= indent {
                    break;
                }
                let (_, access) = value
                    .split_once(':')
                    .ok_or("permissions must use mapping entries")?;
                let access = access.split('#').next().unwrap_or("").trim();
                if !matches!(access, "read" | "write" | "none") {
                    return Err("permission access must be read, write or none".into());
                }
                entries += 1;
            }
            if entries == 0 {
                return Err("empty permissions must be an explicit {} mapping".into());
            }
        }
        if trimmed.starts_with("permissions:")
            && !matches!(trimmed, "permissions:" | "permissions: {}")
        {
            return Err(
                "permissions must use an explicit mapping, never read-all/write-all".into(),
            );
        }
    }
    Ok(())
}

/// Checks exported catalog syntax and typed hint fields only, never inferring
/// idempotency or write safety from their presence.
fn registry_structure(registry: &serde_json::Value) -> Result<(), String> {
    let mut names = std::collections::BTreeSet::new();
    for tool in registry.as_array().ok_or("registry must be a JSON array")? {
        let name = tool["name"]
            .as_str()
            .filter(|name| !name.is_empty())
            .ok_or("tool name is missing")?;
        if !names.insert(name) {
            return Err("tool names must be unique".into());
        }
        if !tool["description"].is_string()
            || tool["inputSchema"]["type"] != "object"
            || tool["inputSchema"]["additionalProperties"] != false
        {
            return Err(format!(
                "{name} requires a description and closed object input schema"
            ));
        }
        let properties = tool["inputSchema"]["properties"]
            .as_object()
            .ok_or("schema properties must be an object")?;
        if let Some(required) = tool["inputSchema"].get("required") {
            let mut keys = std::collections::BTreeSet::new();
            for field in required
                .as_array()
                .ok_or("schema required must be an array")?
            {
                let field = field.as_str().ok_or("required names must be strings")?;
                if !properties.contains_key(field) || !keys.insert(field) {
                    return Err("required fields must be unique declared properties".into());
                }
            }
        }
        for hint in [
            "readOnlyHint",
            "destructiveHint",
            "idempotentHint",
            "openWorldHint",
        ] {
            if !tool["annotations"][hint].is_boolean() {
                return Err(format!("{name} annotation {hint} must be boolean"));
            }
        }
    }
    Ok(())
}

/// Rewrites the pinned digests of the currently managed files.
///
/// The path list itself is deliberately not touched: adding or removing a
/// managed file is a reviewed manifest edit, while `update` only records the
/// new bytes of files already adopted. The manifest is rewritten only when a
/// digest actually changed.
pub fn update(root: &Path) -> Result<(), String> {
    let mut manifest = Manifest::load(root)?;
    let mut changed = false;
    for file in &mut manifest.managed {
        let path: PathBuf = root.join(&file.path);
        let actual =
            digest(&path).map_err(|error| format!("managed file {}: {error}", file.path))?;
        if actual != file.sha256 {
            file.sha256 = actual;
            changed = true;
        }
    }
    if changed {
        let bytes = serde_json::to_vec_pretty(&manifest)
            .map_err(|error| format!("adoption manifest must serialize: {error}"))?;
        std::fs::write(root.join(MANIFEST_PATH), bytes)
            .map_err(|error| format!("{MANIFEST_PATH} must be writable: {error}"))?;
    }
    Ok(())
}

/// Exports or verifies current discovery snapshots from the same domain registries
/// used by live MCP. `export` only writes these three generated files; `check`
/// compares complete JSON including descriptions, schemas and typed annotations.
/// The descriptor contains names, never environment values or capability secrets.
pub fn contract(root: &Path, export: bool) -> Result<(), String> {
    let descriptor = serde_json::json!({
        "schema_version": 1,
        "product_version": env!("CARGO_PKG_VERSION"),
        "sdk": {"name": "rmcp", "version": "3.4.0"},
        "protocol_versions": ["2024-11-05", "2025-03-26", "2025-06-18", "2025-11-25"],
        "operator": {
            "server_name": "agent-run", "registration_name": "agent-run",
            "transport": "stdio", "command": "agent-run", "args": ["mcp"],
            "optional_environment_names": ["AGENT_RUN_HOME"],
            "startup_timeout_seconds": null, "tool_timeout_seconds": null,
            "timeout_policy": "Host chooses startup/call deadlines; cancellation abandons the wait, not admitted work."
        },
        "worker": {
            "server_name": "agent-run-worker",
            "registration_name": agent_run_domain::worker::SERVER_NAME,
            "transport": "stdio", "command": "agent-run", "args": ["_worker-mcp"],
            "required_environment_names": agent_run_domain::worker::ENV_NAMES,
            "startup_timeout_seconds": null, "tool_timeout_seconds": null,
            "supervisor_only": true,
            "timeout_policy": "Supervisor supplies attempt capability; cancelled waits do not undo durable enqueue."
        }
    });
    for (path, value) in [
        (
            "schemas/tools.json",
            serde_json::json!(agent_run_domain::tools::tools_json()),
        ),
        (
            "schemas/worker-tools.json",
            serde_json::json!(agent_run_domain::tools::worker_tools_json()),
        ),
        ("schemas/mcp-registration.json", descriptor),
    ] {
        let mut bytes =
            serde_json::to_vec_pretty(&value).map_err(|_| "contract serialization failed")?;
        bytes.push(b'\n');
        if export {
            std::fs::create_dir_all(root.join("schemas"))
                .map_err(|_| "schema directory unavailable")?;
            std::fs::write(root.join(path), bytes)
                .map_err(|_| format!("{path} must be writable"))?;
        } else if std::fs::read(root.join(path))
            .map_err(|_| format!("{path} missing; run cargo xtask contract export"))?
            != bytes
        {
            return Err(format!(
                "{path} drifted; review cargo xtask contract export"
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    /// Builds just the structural Cargo/workflow/catalog fixture, keeping the
    /// existing minimal digest-verification fixtures independent.
    fn structural_fixture(root: &std::path::Path) {
        adopted(
            root,
            "Cargo.toml",
            r#"[workspace]
    members = ["crates/agent-run"]
    resolver = "3"
    [workspace.package]
    version = "1.2.3"
    edition = "2024"
    publish = false
    license = "MIT"
    rust-version = "1.98.1"
    [workspace.dependencies]
    rmcp = {version = "=3.4.0"}
    [workspace.lints.rust]
    unsafe_op_in_unsafe_fn = "deny"
    [workspace.lints.clippy]
    undocumented_unsafe_blocks = "deny"
    "#,
        );
        adopted(
            root,
            "crates/agent-run/Cargo.toml",
            r#"[package]
    name = "agent-run"
    version.workspace = true
    edition.workspace = true
    publish.workspace = true
    license.workspace = true
    rust-version.workspace = true
    [lints]
    workspace = true
    "#,
        );
        adopted(root, "family.toml", "product = 'agent-run'\n");
        adopted(
            root,
            "rust-toolchain.toml",
            "[toolchain]\nchannel = '1.98.1'\ncomponents = ['rustfmt', 'clippy']\n",
        );
        adopted(
            root,
            "Cargo.lock",
            "[[package]]\nname = 'rmcp'\nversion = '3.4.0'\n",
        );
        adopted(
            root,
            ".github/workflows/ci.yml",
            "permissions:\n  contents: read\njobs:\n  check:\n    steps:\n      - uses: actions/checkout@0123456789012345678901234567890123456789\n",
        );
        super::contract(root, true).unwrap();
    }

    /// Structural checks reject actual missing/drifting declarations without
    /// rewriting them or turning absent fields into a panic.
    #[test]
    fn structural_conformance_rejects_pins_and_inheritance_drift() {
        let root = tempdir().unwrap();
        structural_fixture(root.path());
        super::project_conformance(root.path()).unwrap();
        for (path, before, after) in [
            ("Cargo.toml", "resolver = \"3\"", "resolver = \"2\""),
            ("Cargo.toml", "edition = \"2024\"", "edition = \"2021\""),
            ("Cargo.toml", "publish = false", "publish = true"),
            ("Cargo.toml", "version = \"=3.4.0\"", "version = \"3.4.0\""),
            (
                "crates/agent-run/Cargo.toml",
                "workspace = true",
                "workspace = false",
            ),
            ("rust-toolchain.toml", "1.98.1", "stable"),
            ("Cargo.lock", "3.4.0", "3.3.0"),
            (
                ".github/workflows/ci.yml",
                "0123456789012345678901234567890123456789",
                "v7",
            ),
            (
                ".github/workflows/ci.yml",
                "contents: read",
                "contents: unknown",
            ),
        ] {
            let target = root.path().join(path);
            let original = fs::read_to_string(&target).unwrap();
            let changed = original.replacen(before, after, 1);
            assert_ne!(changed, original);
            fs::write(&target, &changed).unwrap();
            assert!(super::project_conformance(root.path()).is_err(), "{path}");
            assert_eq!(fs::read_to_string(&target).unwrap(), changed);
            fs::write(target, original).unwrap();
        }
        adopted(root.path(), "Cargo.toml", "");
        assert!(super::project_conformance(root.path()).is_err());
    }

    /// Catalog checks validate syntactic required keys and boolean hints only;
    /// no annotation proves that an operation is actually idempotent or safe.
    #[test]
    fn registry_shape_rejects_undeclared_required_and_untyped_hints() {
        let mut tools = serde_json::json!(agent_run_domain::tools::tools_json());
        super::registry_structure(&tools).unwrap();
        tools[0]["inputSchema"]["required"] = json!(["undeclared"]);
        assert!(super::registry_structure(&tools).is_err());
        let mut tools = serde_json::json!(agent_run_domain::tools::worker_tools_json());
        super::registry_structure(&tools).unwrap();
        tools[0]["annotations"]["idempotentHint"] = json!("true");
        assert!(super::registry_structure(&tools).is_err());
    }

    use super::{MANIFEST_PATH, Manifest, verify};
    use serde_json::json;
    use std::fs;
    use tempfile::tempdir;

    /// Writes one valid adoption manifest over the given managed files.
    fn manifest_for(root: &std::path::Path, files: &[(&str, &str)]) {
        let managed: Vec<_> = files
            .iter()
            .map(|(path, bytes)| {
                json!({
                    "path": path,
                    "role": "declaration",
                    "origin": "product",
                    "sha256": sha256_of(bytes),
                })
            })
            .collect();
        let document = json!({
            "schema_version": 1,
            "adoption": "manual",
            "standard_version": "1.0.0-rc.2",
            "template_revision": "7f094e0463c0a6d5cf52d68d91ca32f6bc0f465f",
            "managed": managed,
        });
        fs::create_dir_all(root.join(".family")).unwrap();
        fs::write(
            root.join(MANIFEST_PATH),
            serde_json::to_vec_pretty(&document).unwrap(),
        )
        .unwrap();
        fs::write(
            root.join("family.toml"),
            "standard_version = \"1.0.0-rc.2\"\n",
        )
        .unwrap();
    }

    /// Lowercase SHA-256 hex digest of `bytes`, matching the release digest.
    fn sha256_of(bytes: &str) -> String {
        crate::release::digest_bytes(bytes.as_bytes())
    }

    /// Writes one managed fixture file, creating its parent directory.
    fn adopted(root: &std::path::Path, path: &str, bytes: &str) {
        let target = root.join(path);
        fs::create_dir_all(target.parent().unwrap()).unwrap();
        fs::write(target, bytes).unwrap();
    }

    /// A manifest whose files still match verifies without changing anything.
    #[test]
    fn matching_manifest_verifies() {
        let root = tempdir().unwrap();
        adopted(
            root.path(),
            "family.toml",
            "standard_version = \"1.0.0-rc.2\"\n",
        );
        adopted(root.path(), "docs/family-standard.md", "summary\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        verify(root.path()).expect("matching adoption metadata verifies");
    }

    /// A changed managed file fails verification and names the file.
    #[test]
    fn changed_managed_file_fails_with_its_path() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "edited\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let error = verify(root.path()).expect_err("drifted digest must fail");
        assert!(error.contains("docs/family-standard.md"), "{error}");
        assert!(error.contains("family update"), "{error}");
    }

    /// A missing managed file is a verification failure, not a silent skip.
    #[test]
    fn missing_managed_file_fails() {
        let root = tempdir().unwrap();
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let error = verify(root.path()).expect_err("missing managed file must fail");
        assert!(error.contains("docs/family-standard.md"), "{error}");
    }

    /// The manifest may not pin itself, mirroring the release checksum rule.
    #[test]
    fn manifest_rejects_hashing_itself() {
        let root = tempdir().unwrap();
        manifest_for(root.path(), &[(MANIFEST_PATH, "{}\n")]);
        let error = Manifest::load(root.path()).expect_err("self-hash must be rejected");
        assert!(error.contains("must not hash itself"), "{error}");
    }

    /// Drift between the declaration and the manifest standard version fails.
    #[test]
    fn declaration_must_match_manifest_standard_version() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "summary\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        adopted(
            root.path(),
            "family.toml",
            "standard_version = \"1.0.0-rc.3\"\n",
        );
        let error = verify(root.path()).expect_err("version drift must fail");
        assert!(error.contains("1.0.0-rc.3"), "{error}");
        assert!(error.contains("1.0.0-rc.2"), "{error}");
    }

    /// An initializer-style provenance claim is refused outright.
    #[test]
    fn generated_provenance_is_refused() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "summary\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let raw = fs::read_to_string(root.path().join(MANIFEST_PATH)).unwrap();
        fs::write(
            root.path().join(MANIFEST_PATH),
            raw.replace("\"manual\"", "\"init.sh\""),
        )
        .unwrap();
        let error = Manifest::load(root.path()).expect_err("non-manual adoption must fail");
        assert!(error.contains("manual"), "{error}");
    }

    /// Malformed pins and paths fail before any managed file is read or updated.
    #[test]
    fn malformed_manifest_pins_and_paths_are_refused() {
        let root = tempdir().unwrap();
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        let raw = fs::read_to_string(root.path().join(MANIFEST_PATH)).unwrap();
        let valid: serde_json::Value = serde_json::from_str(&raw).unwrap();
        for field in ["template_revision", "sha256", "path"] {
            let invalid = match field {
                "template_revision" => {
                    vec!["short", "ABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFAB"]
                }
                "sha256" => vec![
                    "short",
                    "ABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFAB",
                ],
                _ => vec!["", "/outside", "../outside", "docs/../outside"],
            };
            for value in invalid {
                let mut document = valid.clone();
                if field == "template_revision" {
                    document[field] = json!(value);
                } else {
                    document["managed"][0][field] = json!(value);
                }
                fs::write(root.path().join(MANIFEST_PATH), document.to_string()).unwrap();
                Manifest::load(root.path()).expect_err("malformed manifest must fail");
                super::update(root.path()).expect_err("update must reject malformed manifest");
                assert_eq!(
                    fs::read_to_string(root.path().join(MANIFEST_PATH)).unwrap(),
                    document.to_string(),
                    "rejected update must not rewrite metadata"
                );
            }
        }
    }

    /// `update` records new bytes only for already-managed paths.
    #[test]
    fn update_rewrites_only_pinned_digests() {
        let root = tempdir().unwrap();
        adopted(root.path(), "docs/family-standard.md", "edited\n");
        manifest_for(root.path(), &[("docs/family-standard.md", "summary\n")]);
        super::update(root.path()).expect("update refreshes digests");
        verify(root.path()).expect("refreshed manifest verifies");
    }

    /// Exported schemas and registration are deterministic; description,
    /// annotation and input drift each fail the read-only contract gate.
    #[test]
    fn contract_export_detects_all_discovery_drift() {
        let root = tempdir().unwrap();
        super::contract(root.path(), true).unwrap();
        super::contract(root.path(), false).unwrap();
        let path = root.path().join("schemas/tools.json");
        let original = fs::read(&path).unwrap();
        for field in ["description", "annotations", "inputSchema"] {
            let mut tools: serde_json::Value = serde_json::from_slice(&original).unwrap();
            tools[0][field] = json!("drift");
            fs::write(&path, tools.to_string()).unwrap();
            assert!(
                super::contract(root.path(), false)
                    .unwrap_err()
                    .contains("drifted")
            );
            assert_eq!(fs::read_to_string(&path).unwrap(), tools.to_string());
        }
        super::contract(root.path(), true).unwrap();
        assert_eq!(fs::read(&path).unwrap(), original);
        super::contract(root.path(), false).unwrap();
    }
}
